apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: db2
  serviceName: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: db2
    spec:
      serviceAccount: {{ .Values.serviceAccount }}
      containers:
        - name: db2
          securityContext:
            privileged: true
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: db2
              containerPort: 50000
          env:
          - name: LICENSE
            value: accept
          - name: DB2INSTANCE
            value: db2inst1
          - name: DB2INST1_PASSWORD
            value: db2inst1
          - name: TO_CREATE_SAMBLEDB
            value: "true"
          volumeMounts:
          - mountPath: /database
            name: db2vol
  volumeClaimTemplates:
  - metadata:
      name: db2vol
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: {{ .Values.storageClassName }}