apiVersion: v1
kind: {{ .Values.route.to.kind }}
metadata:
  name: "{{ .Values.name }}-data"
spec:
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.type }}
  ports:
  - protocol: {{ .Values.ports.protocol }}
    port: {{ .Values.ports.port }}
    targetPort: {{ .Values.ports.targetPort }}