apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mqweb
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: mq-web
  wildcardPolicy: None