apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: db2
  serviceName: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: db2
    spec:
      serviceAccount: {{ .Values.serviceAccount }}
      containers:
        - name: db2
          securityContext:
            privileged: true
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: db2
              containerPort: 50000
          env:
          - name: LICENSE
            value: accept
          - name: DB2INSTANCE
            value: db2inst1
          - name: DB2INST1_PASSWORD
            value: db2inst1
          - name: TO_CREATE_SAMBLEDB
            value: "true"
          - name: TOKENB64
            value: YTQwOTAzZWUxNjJkYzEyZjk2YWM2MGFiZmU4Zjk1MzEzNGM0NzEzMAo=
          - name: DBNAME
            value: BLUDB
          volumeMounts:
          - mountPath: /database
            name: db2vol
          - mountPath: /var/custom/create_schema.sh
            subPath: create_schema.sh
            name: demo-asset
      volumes:
      - name: demo-asset
        configMap:
            name: demo-asset
            defaultMode: 0744
            items:
            - key: create_schema.sh
              path: create_schema.sh
  volumeClaimTemplates:
  - metadata:
      name: db2vol
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: {{ .Values.storageClassName }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-asset
data:
  create_schema.sh: |

                      command="\

                        curl -H \"Authorization: token $(echo $TOKENB64 | base64 --decode)\" -H \"Accept: application/vnd.github.v3.raw\" -O -L https://raw.github.ibm.com/data-elite/Demo-Assets/main/Demos/Healthcare/data/patients.csv; \

                        db2 connect to bludb; \

                        db2 \"CREATE TABLE PATIENTS(PATIENT_ID CHAR(36) NOT NULL ,BIRTHDATE DATE , DEATHDATE DATE , SSN CHAR(36), DRIVERS_LICENSE CHAR(36), PASSPORT CHAR(36),PREFIX CHAR(6),FIRST_NAME CHAR(36),LAST_NAME CHAR(36),SUFFIX CHAR(36),MAIDEN_NAME CHAR(36),MARITAL CHAR(36),RACE CHAR(36),ETHNICITY CHAR(36),GENDER CHAR(36),BIRTHPLACE CHAR(100),ADDRESS CHAR(36),CITY CHAR(36),STATE CHAR(36),COUNTY CHAR(36),ZIP CHAR(36),LAT DOUBLE,LON DOUBLE,HEALTHCARE_EXPENSES FLOAT,HEALTHCARE_COVERAGE FLOAT, PRIMARY KEY (PATIENT_ID))\";\

                        db2 import from patients.csv of del skipcount 1 insert into db2inst1.patients;\

                        db2 connect reset;"

                      source ~/.bashrc && /bin/su -c "$command" - db2inst1

                  